In [3]:
import pandas as pd

df = pd.read_csv('Hospital Emergency Room Data.csv')

In [4]:
df.head()

,Patient Id,Patient Admission Date,Patient First Inital,Patient Last Name,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime,Patient Admission Flag.1
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,NaN,False,10.0,39,False
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,NaN,True,NaN,27,True
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,True
3,358-31-9711,04-02-2024 22:34,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,True
4,289-26-0537,04-09-2024 17:48,Y,Gionettitti,Male,5,African American,Orthopedics,False,NaN,10,False

In [5]:
df['Department Referral']=df['Department Referral'].fillna(df['Department Referral'].mode()[0])

In [6]:
df['Patient Satisfaction Score']=df['Patient Satisfaction Score'].fillna(df['Patient Satisfaction Score'].median())

In [7]:
print(df.isnull().sum())

Patient Id                    0
Patient Admission Date        0
Patient First Inital          0
Patient Last Name             0
Patient Gender                0
Patient Age                   0
Patient Race                  0
Department Referral           0
Patient Admission Flag        0
Patient Satisfaction Score    0
Patient Waittime              0
Patient Admission Flag.1      0
dtype: int64

In [31]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df=df.rename(columns={'patient_admission_date':'admission_date'})
df=df.rename(columns={'first_inital':'first_name'})

In [32]:
df.columns

Index(['patient_id', 'admission_date', 'first_name', 'last_name', 'gender',
       'age', 'race', 'department_referral', 'admission_flag',
       'satisfaction_score', 'waittime', 'admission_flag.1'],
      dtype='object')

In [30]:
df.rename(columns={'id': 'patient_id'}, inplace=True)

print(df.columns.tolist())

['patient_id', 'admission_date', 'first_inital', 'last_name', 'gender', 'age', 'race', 'department_referral', 'admission_flag', 'satisfaction_score', 'waittime', 'admission_flag.1']

In [35]:
labels=['Young Adult','Adult','Middle-Aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4, labels=labels)

In [36]:
df[['age','age_group']].head(10)

   age    age_group
0   69       Senior
1    4  Young Adult
2   56  Middle-Aged
3   24        Adult
4    5  Young Adult
5   58  Middle-Aged
6   68       Senior
7   47  Middle-Aged
8   79       Senior
9   62       Senior

In [37]:

# Remove the duplicate admission flag column
df.drop(columns=['admission_flag.1'], inplace=True)

# Check the remaining columns
print(df.columns.tolist())

['patient_id', 'admission_date', 'first_name', 'last_name', 'gender', 'age', 'race', 'department_referral', 'admission_flag', 'satisfaction_score', 'waittime', 'age_group']

In [38]:
df.head()

,patient_id,admission_date,first_name,last_name,gender,age,race,department_referral,admission_flag,satisfaction_score,waittime,age_group
0,145-39-5406,20-03-2024 08:47,H,Glasspool,M,69,White,General Practice,False,10.0,39,Senior
1,316-34-3057,15-06-2024 11:29,X,Methuen,M,4,Native American/Alaska Native,General Practice,True,5.0,27,Young Adult
2,897-46-3852,20-06-2024 09:13,P,Schubuser,F,56,African American,General Practice,True,9.0,55,Middle-Aged
3,358-31-9711,04-02-2024 22:34,U,Titcombe,F,24,Native American/Alaska Native,General Practice,True,8.0,31,Adult
4,289-26-0537,04-09-2024 17:48,Y,Gionettitti,Male,5,African American,Orthopedics,False,5.0,10,Young Adult

In [39]:

# Convert admission_date into datetime format
df['admission_date'] = pd.to_datetime(
    df['admission_date'],
    dayfirst=True,
    errors='coerce'
)

# Create separate date and time columns
df['admission_time'] = df['admission_date'].dt.strftime('%H:%M')
df['admission_date'] = df['admission_date'].dt.strftime('%d-%m-%Y')

# Display the result
display(df[['patient_id', 'admission_date', 'admission_time']].head(10))

    patient_id admission_date admission_time
0  145-39-5406     20-03-2024          08:47
1  316-34-3057     15-06-2024          11:29
2  897-46-3852     20-06-2024          09:13
3  358-31-9711     04-02-2024          22:34
4  289-26-0537     04-09-2024          17:48
5  255-51-2877     20-04-2023          00:13
6  465-97-0990     23-08-2023          08:26
7  157-31-7520     29-07-2023          16:57
8  432-34-5614     19-02-2024          06:54
9  609-17-8678     11-10-2024          05:25

In [40]:

# Correct patient IDs with sequential numbers
df['patient_id'] = range(1, len(df) + 1)

# Display the first 10 patient IDs
display(df[['patient_id']].head(10))

# Check that all IDs are unique
print("Total patient records:", len(df))
print("Unique patient IDs:", df['patient_id'].nunique())

   patient_id
0           1
1           2
2           3
3           4
4           5
5           6
6           7
7           8
8           9
9          10

Total patient records: 9216
Unique patient IDs: 9216

In [47]:
df.head()

,patient_id,admission_date,first_name,last_name,gender,age,race,department_referral,admission_flag,satisfaction_score,waiting_time_minutes,age_group
0,1,2024-03-20 08:47:00,H,Glasspool,Male,69,White,General Practice,False,10.0,39 min,Senior
1,2,2024-06-15 11:29:00,X,Methuen,Male,4,Native American/Alaska Native,General Practice,True,5.0,27 min,Young Adult
2,3,2024-06-20 09:13:00,P,Schubuser,Female,56,African American,General Practice,True,9.0,55 min,Middle-Aged
3,4,2024-02-04 22:34:00,U,Titcombe,Female,24,Native American/Alaska Native,General Practice,True,8.0,31 min,Adult
4,5,2024-09-04 17:48:00,Y,Gionettitti,Male,5,African American,Orthopedics,False,5.0,10 min,Young Adult

In [42]:

# Merge date and time into one column
df['admission_date'] = pd.to_datetime(
    df['admission_date'].astype(str) + ' ' +
    df['admission_time'].astype(str),
    format='%d-%m-%Y %H:%M',
    errors='coerce'
)

# Remove the separate time column
df.drop(columns=['admission_time'], inplace=True)

# Display the result
display(df[['patient_id', 'admission_date']].head(10))

   patient_id      admission_date
0           1 2024-03-20 08:47:00
1           2 2024-06-15 11:29:00
2           3 2024-06-20 09:13:00
3           4 2024-02-04 22:34:00
4           5 2024-09-04 17:48:00
5           6 2023-04-20 00:13:00
6           7 2023-08-23 08:26:00
7           8 2023-07-29 16:57:00
8           9 2024-02-19 06:54:00
9          10 2024-10-11 05:25:00

In [43]:

# Standardize gender values
df['gender'] = (
    df['gender']
    .astype('string')
    .str.strip()
    .str.lower()
    .replace({
        'm': 'Male',
        'male': 'Male',
        'f': 'Female',
        'female': 'Female'
    })
)

# Check the results
print(df['gender'].value_counts(dropna=False))

gender
Male      4729
Female    4487
Name: count, dtype: Int64

In [45]:

# Rename waiting time column to indicate minutes
df.rename(
    columns={'waittime': 'waiting_time_minutes'},
    inplace=True
)

# Display the result
display(df[['patient_id', 'waiting_time_minutes']].head(10))

   patient_id  waiting_time_minutes
0           1                    39
1           2                    27
2           3                    55
3           4                    31
4           5                    10
5           6                    59
6           7                    43
7           8                    23
8           9                    42
9          10                    51

In [46]:

# Display waiting time with the 'min' suffix
df['waiting_time_minutes'] = (
    df['waiting_time_minutes'].astype(str) + ' min'
)

# Display the result
display(df[['patient_id', 'waiting_time_minutes']].head(10))

   patient_id waiting_time_minutes
0           1               39 min
1           2               27 min
2           3               55 min
3           4               31 min
4           5               10 min
5           6               59 min
6           7               43 min
7           8               23 min
8           9               42 min
9          10               51 min

In [48]:

df.rename(
    columns={'waiting_time_minutes': 'waiting_time'},
    inplace=True
)

display(df[['patient_id', 'waiting_time']].head(10))

   patient_id waiting_time
0           1       39 min
1           2       27 min
2           3       55 min
3           4       31 min
4           5       10 min
5           6       59 min
6           7       43 min
7           8       23 min
8           9       42 min
9          10       51 min

In [49]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.13-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\lenovo\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Downloading psycopg2_binary-2.9.13-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ------------------ --------------------- 1.3/2.8 MB 8.8 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 7.0 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 4.0 MB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 3.0 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.13
Note: you may need to restart the kernel to use updated packages.

WARNING: Cache entry deserialization failed, entry ignored

In [50]:
import sqlalchemy
import psycopg2

print("SQLAlchemy version:", sqlalchemy.__version__)
print("Psycopg2 version:", psycopg2.__version__)
print("Both packages installed successfully!")

SQLAlchemy version: 2.0.39
Psycopg2 version: 2.9.13 (dt dec pq3 ext lo64)
Both packages installed successfully!

In [53]:
from sqlalchemy import create_engine

username = "postgres"          # Default user
password = "Siddhi123"     # Password set during PostgreSQL installation
host = "localhost"             # If running locally
port = "5432"                  # Default PostgreSQL port
database = "Hospital_Emergency" # Database created in pgAdmin

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)

# Step 2: Load DataFrame into PostgreSQL
table_name = "Patient"        # Choose any table name

df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'Patient' in database 'Hospital_Emergency'.